### ISSUE TITLE
Seleccionar solo canales Españoles en lista Pluto.TV

### ISSUE THREAD

**Issue by cvc90** [davidmuma/Canales_dobleM#1]
Existe la posibilidad de seleccionar solo los canales españoles en la lista Pluto.TV?

De esa manera se reduciría bastante la lista de canales, ya que la majoria de idiomas no son de interès, algunos son repetidos cambiando idioma y hacen que relentizen la carga.

**Comment by davidmuma** [comment]
Estudiaré la forma de poder seleccionar el idioma en la lista de Pluto
