### ISSUE TITLE
Compatibilidad DSM 7

### ISSUE THREAD

**Issue by heisenbuglab** [davidmuma/Canales_dobleM#2]
Buenos días,

He actualizado el synology a DSM 7 y veo que no hace nada cuando selecciono la opción 1 (donde se especifica "DSM6").

¿Se puede añadir compatibilidad?

Gracias,

**Comment by davidmuma** [comment]
Buenas, no voy a modificar el script para hacerlo compatible con DSM 7, tendrás que pasar tvheadend a docker y usar el nuevo script

**Comment by heisenbuglab** [comment]
Es una lástima, porque la versión de docker oficial no deja vincular OSCAM. Igual tendría que buscar otro paquete...

No está el apartado "Configuración/CAs" donde enlazas una cosa con otra. Además, si utilizo la versión docker no puedo aprovechar la aceleración por hardware (no puedes hacer GPU decoding con ffmpeg). Cosa que con la versión DSM tvheadend de Th0ma7 si me permite hacer ambas cosas.
( eso dicen aquí: https://github.com/th0ma7/synology/issues/7 )

Me encantaría seguir utilizando tu script. Si no lo puedes hacer compatible, podrías indicarme que paquete de docker utilizar? para probarlo.

EDIT: para la pestaña CAs, solo había que habilitar el modo experto. Funcionando correctamente. 

Gracias

**Comment by davidmuma** [comment]
Usa la versión de linuxserver, tiene aceleración por hardware. Muchos estamos usando tvheadend por docker y todos coincidimos en que funciona mejor
