### ISSUE TITLE
Mantener lista canales propia

### ISSUE THREAD

**Issue by vusky** [davidmuma/Canales_dobleM#3]
Hola, en teoría cuando instalas la lista del script, dice que no debería tocar las listas propias ya creadas y hasta cierto punto lo hace
Pero en mi caso, tengo una lista personalizada de los canales Satélite HD con mi orden y el script la sobre escribe con la lista de Astra Individual, si o si

En cambio la lista que tengo de la TDT, no la toca

La instalación que uso previa, viene del script NORMANDY, pero creo no debería influir

Por lo demás el script va muy bien, tanto como el medio difunto NORMANDY, que tiene (hasta que deje de funcionar, por que creo ya no lo mantienen) opciones muy interesantes y integradas dentro del frontend que van perfectas para el usuario de a pie

Saludos

**Comment by davidmuma** [comment]
Buenas...

Te sobreescribe todos los los canales de tu lista de satélite o solo algunos?

**Comment by vusky** [comment]
Todos
Mantiene la TDT, incluso el grupo, pero desactiva el sintonizador, hay que volver a marcarlo como activo

**Comment by davidmuma** [comment]
Lo del sintonizador cuando se hace una instalación nueva es normal, si actualizas no te desactiva el sintonizador. 
Respecto a lo de que te sobrescribe los canales de satélite, le daré una vuelta al script, porque he hecho pruebas creando una lista de canales en tvheadend y luego actualizando con e script y me la ha mantenido sin tocarla
