### ISSUE TITLE
Compatibilidad con Alpine linux

### ISSUE THREAD

**Issue by djjul** [davidmuma/Canales_dobleM#4]
Tengo un pequeño problema y es que cuando corre en Alpine linux no existe systemctl sino rc-service con la sintaxis:

rc-service {service-name} start

Gracias por la aportación.

**Comment by davidmuma** [comment]
El script no está adaptado para Alpine, inténtalo con el de Docker a ver si te funciona

**Comment by djjul** [comment]
Hola David, no me funcionó pero no te preocupes yo ya estoy intentando algo con Debian, si no hay demanda en Alpine linux lo damos por cerrado y ya está.

Gracias por todo.
