### ISSUE TITLE
Incorporar este epg a lista iptv via kodi pvr iptv simple

### ISSUE THREAD

**Issue by Leor2208** [davidmuma/Canales_dobleM#5]
Buenos días,
Es posible incorporar esta información de la programación a los canales de una lista iptv en kodi con el plugin pvr iptv simple?
Un saludo!
Leo

**Comment by miguelcabanes** [comment]
Si, es posible. Yo lo uso así. Lo que tienes que tener en cuenta para que te funcione es que los nombres de tus canales IPTV coincidan con los de esta guía
