### ISSUE TITLE
Opcion de añadir lista con fanart a threadfin

### ISSUE THREAD

**Issue by davidclaeysquinones** [davidmuma/Canales_dobleM#8]
[Threadfin](https://github.com/Threadfin/Threadfin) es un programa muy util para recompilar el epg de varias fuentes.
Estaria bien si existiera alguna opcion para poder usar las fuentes de epg con fanart en este programa.

**Comment by davidmuma** [comment]
Eso no depende de mi, tendrás que pedírselo al desarrollador de Threadfin
